import "./globals.css"

export const metadata = {
    title: 'MessangerClone',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        {children}
        <div className="bg-circle-1"/>
        <div className="bg-circle-2"/>
        </body>
        </html>
    )
}
