import "./style/globals.css"
import {Providers} from "./lib/providers";

export const metadata = {
    title: 'MessangerClone',
    description: 'Generated by create next app',
}
export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <main>
            <Providers>
                <div className="h-dvh flex items-center justify-center">
                    {children}
                </div>
            </Providers>
        </main>
        <div className="bg-circle-1"/>
        <div className="bg-circle-2"/>
        </body>
        </html>
    )
}
